### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by siju-samuel** [zoezhou1999/BeautifyBasedOnGAN#1]
Thanks for the very good paper. Could you please share the pretrained model as well.

**Comment by zoezhou1999** [comment]
Haha, not the very good paper. It will continue to be revised. I am busy these days. I will share models after these days. :)

**Comment by siju-samuel** [comment]
@zoezhou1999 The pretrained model is ready to share? Thanks in advance.

**Comment by zoezhou1999** [comment]
@siju-samuel  I think I have shared the models, please refer to the repo, except the Beholder-GAN model we reproduced. Is the Beholder the model you are seeking for?
